# Generated by Django 5.2.16 on 2026-09-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['sort_order', models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-id'], 'verbose_name': 'job posting'},
        ),
    ]
