# Generated by Django 5.2.16 on 2026-08-17 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(blank=True, help_text='An address with no admin account. Blank on staff rows.', max_length=254)),
                ('user', models.ForeignKey(blank=True, help_text='A staff account. Deleting the account removes the subscription.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'email', 'user_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('email', ''), ('user__isnull', False)), models.Q(('user__isnull', True), models.Q(('email', ''), _negated=True)), _connector='OR'), name='notification_recipient_user_xor_email'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='uniq_notification_recipient_user_per_event'), models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('event', 'email'), name='uniq_notification_recipient_email_per_event')],
            },
        ),
    ]
