# Generated by Django 5.2.16 on 2026-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_owner_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
