# Generated by Django 5.2.16 on 2026-07-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_productimage_productvideo'),
        ('core', '0003_seed_countries_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variant', 'currency', 'country', 'starts_at'), name='uniq_price_scope')],
            },
        ),
    ]
