import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Backend media (seeded product/category images) in dev, plus the production media
    // CDN when one is configured.
    //
    // Production images live in a PRIVATE S3 bucket and are served through CloudFront
    // with Origin Access Control. The bucket stays private on purpose: the nightly
    // Postgres backups share it (`backups/` alongside `catalog/`, see
    // infra/deploy/backup.sh), so granting public read would mean switching off Block
    // Public Access on the bucket that holds the database dumps. See docs/architecture.md.
    //
    // Env-driven so this file is inert until the distribution exists — with
    // NEXT_PUBLIC_MEDIA_HOST unset, behaviour is exactly as before.
    remotePatterns: [
      { protocol: "http", hostname: "localhost", port: "8000", pathname: "/media/**" },
      ...(process.env.NEXT_PUBLIC_MEDIA_HOST
        ? [
            {
              protocol: "https" as const,
              hostname: process.env.NEXT_PUBLIC_MEDIA_HOST,
              // `/catalog/**`, never `/**`: the optimizer must refuse to proxy anything
              // but catalog media even if another prefix ever becomes reachable.
              pathname: "/catalog/**",
            },
          ]
        : []),
    ],
    // Next 16 breaking change (version-16.md § "Local IP Restriction"): the image
    // optimizer refuses to fetch upstreams that resolve to a private/loopback IP.
    // Our dev backend serves /media from localhost (127.0.0.1/::1), so seeded
    // catalog images 400 without this. GATED to development only — in production
    // the SSRF guard must stay ON (defense-in-depth against DNS-rebinding /
    // internal-IP fetch through a remotePatterns-allowed host once Plan-22 adds a
    // remote media origin). NODE_ENV is "development" under `npm run dev`.
    dangerouslyAllowLocalIP: process.env.NODE_ENV !== "production",
    // Local, self-authored SVG art only (public/home/**, generated by
    // scripts/gen-placeholders.mjs). NEVER feed user-supplied or remote SVGs
    // through the optimizer — the CSP sandbox below is the backstop.
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
