import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Backend media (seeded product/category images) in dev. Plan-22 adds the
    // production media host here.
    remotePatterns: [
      { protocol: "http", hostname: "localhost", port: "8000", pathname: "/media/**" },
    ],
    // Next 16 breaking change (version-16.md § "Local IP Restriction"): the image
    // optimizer refuses to fetch upstreams that resolve to a private/loopback IP.
    // Our dev backend serves /media from localhost (127.0.0.1/::1), so seeded
    // catalog images 400 without this. GATED to development only — in production
    // the SSRF guard must stay ON (defense-in-depth against DNS-rebinding /
    // internal-IP fetch through a remotePatterns-allowed host once Plan-22 adds a
    // remote media origin). NODE_ENV is "development" under `npm run dev`.
    dangerouslyAllowLocalIP: process.env.NODE_ENV !== "production",
    // Local, self-authored SVG art only (public/home/**, generated by
    // scripts/gen-placeholders.mjs). NEVER feed user-supplied or remote SVGs
    // through the optimizer — the CSP sandbox below is the backstop.
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

export default nextConfig;
