import type { NextConfig } from "next";
import { CSP_HEADER_NAME, buildCsp } from "./src/lib/csp";

const nextConfig: NextConfig = {
  images: {
    // Backend media (seeded product/category images) in dev, plus the production media
    // CDN when one is configured.
    //
    // Production images live in a PRIVATE S3 bucket and are served through CloudFront
    // with Origin Access Control. The bucket stays private on purpose: the nightly
    // Postgres backups share it (`backups/` alongside `catalog/`, see
    // infra/deploy/backup.sh), so granting public read would mean switching off Block
    // Public Access on the bucket that holds the database dumps. See docs/architecture.md.
    //
    // The CDN hostname is a PUBLIC value (it appears in every product page's HTML), so
    // it is committed as the default rather than living only in a Vercel env var —
    // the env var still overrides it (e.g. pointing previews at a different
    // distribution), but a missing dashboard entry can no longer break every product
    // image in production, which is exactly what happened before this default existed.
    remotePatterns: [
      { protocol: "http", hostname: "localhost", port: "8000", pathname: "/media/**" },
      {
        protocol: "https" as const,
        hostname: process.env.NEXT_PUBLIC_MEDIA_HOST ?? "dk4ivng9pnc2t.cloudfront.net",
        // `/catalog/**`, never `/**`: the optimizer must refuse to proxy anything
        // but catalog media even if another prefix ever becomes reachable.
        pathname: "/catalog/**",
      },
    ],
    // Next 16 breaking change (version-16.md § "Local IP Restriction"): the image
    // optimizer refuses to fetch upstreams that resolve to a private/loopback IP.
    // Our dev backend serves /media from localhost (127.0.0.1/::1), so seeded
    // catalog images 400 without this. GATED to development only — in production
    // the SSRF guard must stay ON (defense-in-depth against DNS-rebinding /
    // internal-IP fetch through a remotePatterns-allowed host once Plan-22 adds a
    // remote media origin). NODE_ENV is "development" under `npm run dev`.
    dangerouslyAllowLocalIP: process.env.NODE_ENV !== "production",
    // Local, self-authored SVG art only (public/home/**, generated by
    // scripts/gen-placeholders.mjs). NEVER feed user-supplied or remote SVGs
    // through the optimizer — the CSP sandbox below is the backstop.
    dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
};

/**
 * Security headers (Plan-25 task 2).
 *
 * CSP is REPORT-ONLY on the storefront — see `src/lib/csp.ts` for why, and for the list
 * of third-party payment origins it had to be built around. The API's own headers
 * (HSTS, nosniff, X-Frame-Options) are set by Django on `api.` and are not duplicated
 * here; these apply to the pages the browser actually renders.
 */
nextConfig.headers = async () => [
  {
    source: "/:path*",
    headers: [
      { key: CSP_HEADER_NAME, value: buildCsp({ dev: process.env.NODE_ENV !== "production" }) },
      // Belt and braces with frame-ancestors above, for anything that predates CSP.
      { key: "X-Frame-Options", value: "DENY" },
      { key: "X-Content-Type-Options", value: "nosniff" },
      { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
      // The storefront needs none of these. Naming them is what stops a future dependency
      // quietly asking the customer for their camera on a checkout page.
      { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
    ],
  },
];

export default nextConfig;
