# Generated by Django 5.2.16 on 2026-09-03 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0012_productimage_thumbnail'),
        ('core', '0011_businessdecisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='combos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('available_countries', models.ManyToManyField(blank=True, related_name='combos', to='core.country')),
            ],
            options={
                'ordering': ['position', '-published_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='combos.combo')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combo_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('combo', 'variant'), name='uniq_combo_variant'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='combo_item_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='ComboPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='combos.combo')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('combo', 'country'), name='uniq_combo_price_market')],
            },
        ),
    ]
