# Generated by Django 5.2.16 on 2026-09-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0002_combo_image_under_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='gift_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='catalog/combos/gifts/'),
        ),
        migrations.AddField(
            model_name='combo',
            name='gift_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='combo',
            name='reward_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('gift', 'Free gift')], default='discount', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='combo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reward_type', 'gift'), _negated=True), models.Q(('gift_name__regex', '^\\s*$'), _negated=True), _connector='OR'), name='combo_gift_reward_needs_a_gift'),
        ),
    ]
