# Generated by Django 5.2.16 on 2026-07-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_countries_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area_label',
            field=models.CharField(default='Area', max_length=30),
        ),
    ]
