# Generated by Django 5.2.16 on 2026-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_country_state_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_tax', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'store settings',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='charge_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='tax_applies_to_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='tax_label',
            field=models.CharField(default='Tax', max_length=30),
        ),
    ]
