# Generated by Django 5.2.16 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_tax_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDecisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_discount_first_order_only', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'business decisions',
            },
        ),
    ]
