# Generated by Django 5.2.16 on 2026-09-03 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_unique_together_cartcombogroup'),
        ('catalog', '0012_productimage_thumbnail'),
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcombogroup',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_groups', to='combos.combo'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='combo_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cartcombogroup'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('combo_group__isnull', True)), fields=('cart', 'variant'), name='uniq_standalone_cart_line'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('combo_group__isnull', False)), fields=('combo_group', 'variant'), name='uniq_combo_cart_line'),
        ),
    ]
