# Generated by Django 5.2.16 on 2026-09-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartcombogroup_combo_cartitem_combo_group_and_more'),
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartcombogroup',
            constraint=models.UniqueConstraint(fields=('cart', 'combo'), name='uniq_cart_combo_group'),
        ),
    ]
