# Generated by Django 5.2.16 on 2026-08-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('core', '0006_auditlog_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('collection_carousel', 'Collection carousel'), ('banner_grid', 'Banner grid'), ('editorial', 'Editorial'), ('brand_strip', 'Brand strip')], max_length=30)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='cms/banners/')),
                ('mobile_image', models.ImageField(blank=True, upload_to='cms/banners/')),
                ('cta_text', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('placement', models.CharField(choices=[('hero', 'Hero'), ('strip', 'Announcement strip'), ('category', 'Category')], default='strip', max_length=20)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='banners', to='core.country')),
            ],
            options={
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=300)),
                ('menu', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='footer', max_length=10)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
            ],
            options={
                'ordering': ['menu', 'sort', 'id'],
            },
        ),
    ]
