# Generated by Django 5.2.16 on 2026-08-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_homepagesection_banner_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('review_url', models.URLField()),
                ('reviewed_at_text', models.CharField(blank=True, max_length=60)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleReviewsMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('review_count_text', models.CharField(default='', max_length=40)),
                ('profile_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'google reviews meta',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
