# Generated by Django 5.2.16 on 2026-08-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_landing_redesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='video_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, upload_to='cms/banners/'),
        ),
    ]
