# Generated by Django 5.2.16 on 2026-08-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_banner_media_under_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero slide'), ('strip', 'News marquee item'), ('category', 'Shop-by-category tile'), ('concern', 'Shop-by-concern tile'), ('feature', 'Glow Set feature'), ('feature_nature', 'tokè × natural tile'), ('feature_collection', 'Toke Naturals tile'), ('men', 'Men section banner'), ('women', 'Women section banner'), ('babies', 'Babies section banner'), ('tiktok', 'TikTok section banner'), ('trio', 'Collections trio tile')], default='strip', max_length=20),
        ),
    ]
