# Generated by Django 5.2.16 on 2026-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_mediaasset_banner_image_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video_mode',
            field=models.CharField(choices=[('loop', 'Loop silently'), ('click', 'Play on click')], default='loop', max_length=5),
        ),
    ]
