# Generated by Django 5.2.16 on 2026-08-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_banner_video_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('hero', 'Hero slide'), ('strip', 'News marquee item'), ('category', 'Shop-by-category tile'), ('concern', 'Shop-by-concern tile'), ('feature', 'Glow Set feature'), ('feature_nature', 'tokè × natural tile'), ('feature_collection', 'Toke Naturals tile'), ('men', 'Men section banner'), ('women', 'Women section banner'), ('babies', 'Babies section banner'), ('tiktok', 'TikTok section banner'), ('trio', 'Collections trio tile'), ('affiliate_hero', 'Affiliates page — hero image'), ('affiliate_tier', 'Affiliates page — ₦200k Club image')], default='strip', max_length=20),
        ),
    ]
