# Generated by Django 5.2.16 on 2026-08-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_banner_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlereview',
            name='review_url',
            field=models.URLField(max_length=500),
        ),
    ]
