# Generated by Django 5.2.16 on 2026-09-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_trainingresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mode',
            field=models.CharField(choices=[('overlay', 'Photo — the site writes the headline and button over it'), ('artwork', 'Finished artwork — show it whole, the site adds no text')], default='overlay', max_length=7),
        ),
    ]
