# Generated by Django 5.2.16 on 2026-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_number_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_reason',
            field=models.TextField(blank=True),
        ),
    ]
