# Generated by Django 5.2.16 on 2026-07-16 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('core', '0004_country_area_label'),
        ('orders', '0004_orderevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'reservation_expires_at'], name='orders_orde_status_adb568_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-placed_at'], name='orders_orde_status_ab153f_idx'),
        ),
    ]
