# Generated by Django 5.2.16 on 2026-08-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
