# Generated by Django 5.2.16 on 2026-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderitem_image_url_orderitem_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
