# Generated by Django 5.2.16 on 2026-08-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_tax_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_store',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
