# Generated by Django 5.2.16 on 2026-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_pickup_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
