# Generated by Django 5.2.16 on 2026-09-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_referral_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='combo_discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
