# Generated by Django 5.2.16 on 2026-09-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_combo_discount_total_orderitem_combo_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo_gift',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
