"""The WordPress hasher, pinned against hashes generated by the production server's PHP.

WHERE THESE VECTORS CAME FROM. Not from this implementation, and not from a blog post:
they were generated on the live VPS by PHP 8.1.34 — the same interpreter that wrote every
hash this migration will read — using `password_hash()` and WordPress's own
`wp-includes/class-phpass.php`. A test that verified my phpass port against my phpass port
would pass just as happily while being wrong, and the cost of being wrong here is 937
people locked out of their accounts on cutover day.

The passwords are synthetic. No customer material is in this file.
"""

import pytest
from django.contrib.auth.hashers import check_password, identify_hasher, is_password_usable

from apps.accounts.hashers import PREFIX, WordPressPasswordHasher, wrap_wordpress_hash

# (password, $wp$ hash, phpass hash, plain bcrypt hash) — see the module docstring.
VECTORS = [
    (
        "correct horse battery staple",
        "$wp$2y$10$IUlIfwjT7HHIH3No4zfCpuLzUf5sWcFH/SxaizU89nbzdpSLDgb5W",
        "$P$BGdO4mJuXs9duABdLgHQmT8H.LClvv.",
        "$2y$10$dbpSi/acYYKp4meIdxjX4epJcumjNq9F7ejymIgLwoGNenHXWm3Ay",
    ),
    (
        "p@ssw0rd!",
        "$wp$2y$10$PmVKoYbjxb47nzGmq2e.U.Pekrdm7BB.8ChJP7ctUdIETELJXZzuq",
        "$P$BNZC0ftX9Wuz4wCjCksD1X5DgUSg0r.",
        "$2y$10$ZMQyVawYWMpOCayx.JXRjuSWe0mXYQg6arHKKqHqzv1R0ebmp2hhC",
    ),
    (
        "Tökè Cøsmétics ✨",
        "$wp$2y$10$DD2ZIbflJ2eQev.U4vWTVurxhgMrbPGBD8CLomia3ifi/AC2sClIq",
        "$P$B7pEsTkbBSDZsngaLxYZrCkkJ.p57w1",
        "$2y$10$5MiDVzYHctO0dhNwN33utuGu5bGDl8oumD3us3kNamxySxzqve6yq",
    ),
    (
        "A" * 100 + "ZZZ_TAIL",
        "$wp$2y$10$Xlr1qsan8OCmHnz1gpVYHuO4ZORXoihHU7.OeapfPcA17lOnWdu0O",
        "$P$BXLo2RI7ek0ME6Euw/HJMOW1sqObvT1",
        "$2y$10$OtYA0ChOqdQisgjMICE6TOa2A.hnnGaDIUOq8zj2grq6/fZYwFv46",
    ),
    (
        "x",
        "$wp$2y$10$ReSNFgjqf5vUQ39aCcRTXeyo0O1Qz5yP1B5G3z1RIt4o2iXTa53Sm",
        "$P$BNythS5nTH6mgVP6mxLrgMlCajXCNS/",
        "$2y$10$LO4jc8yZ..tRCkFHYr5uJOyay7jo5EVfFjKUszx/v54jsm/WEWKzO",
    ),
]

FORMATS = ["wp_modern", "phpass", "bcrypt"]


def _cases():
    for password, wp_modern, phpass, plain in VECTORS:
        for name, raw in zip(FORMATS, (wp_modern, phpass, plain)):
            yield pytest.param(password, raw, id=f"{name}-{password[:12]}")


@pytest.mark.parametrize("password,raw", list(_cases()))
def test_verifies_hashes_generated_by_the_production_php(password, raw):
    assert WordPressPasswordHasher().verify(password, PREFIX + raw)


@pytest.mark.parametrize("password,raw", list(_cases()))
def test_rejects_the_wrong_password(password, raw):
    # The difference goes at the FRONT. Appending would land past bcrypt's 72-byte
    # truncation point for the long vector, where PHP would accept it too — so a suffix
    # would be asserting a lockout bug rather than a rejection. The truncation itself is
    # asserted deliberately below.
    assert not WordPressPasswordHasher().verify("!" + password, PREFIX + raw)


def test_UNICODE_IS_UTF8_NOT_LATIN1():
    # PHP hashes bytes and has no opinion about encoding; Python must therefore pick the
    # same one WordPress's forms submit. Getting this wrong would lock out exactly the
    # customers with accented names — a failure that would look random from the outside.
    password, wp_modern, phpass, plain = VECTORS[2]
    assert "✨" in password
    for raw in (wp_modern, phpass, plain):
        assert WordPressPasswordHasher().verify(password, PREFIX + raw)


def test_THE_PRE_HASH_IS_WHY_LONG_PASSWORDS_ARE_NOT_INTERCHANGEABLE():
    """bcrypt truncates at 72 bytes. `$wp$` exists to stop that mattering.

    Two passwords sharing their first 72 bytes are the SAME password to plain bcrypt.
    This test asserts that difference rather than describing it, because it is the entire
    justification for the HMAC-SHA384 step — if the `$wp$` branch ever quietly lost the
    pre-hash, every long password would start accepting its own prefix and nothing else
    in the suite would notice.
    """
    real = VECTORS[3][0]
    collides = "A" * 100 + "ZZZ_DIFF"  # same first 72 bytes, different password
    assert real[:72] == collides[:72] and real != collides

    hasher = WordPressPasswordHasher()
    # Plain bcrypt: the imposter gets in. This is WordPress's old behaviour, preserved
    # faithfully — those rows are what they are.
    assert hasher.verify(collides, PREFIX + VECTORS[3][3])
    # $wp$: it does not.
    assert not hasher.verify(collides, PREFIX + VECTORS[3][1])
    assert hasher.verify(real, PREFIX + VECTORS[3][1])


@pytest.mark.parametrize(
    "junk",
    ["!locked", "!", "", "garbage", "$P$", "$P$B", "$wp$", "$2y$", PREFIX, PREFIX + "!locked"],
)
def test_MALFORMED_HASHES_FAIL_THE_LOGIN_RATHER_THAN_500_IT(junk):
    # A truncated or locked row must be a failed password, not an exception on the login
    # endpoint. `!locked` is real: it appears in these tables.
    assert WordPressPasswordHasher().verify("anything", junk) is False


def test_phpass_rejects_an_absurd_iteration_count():
    # phpass's own bounds are 7..30. Without them a crafted `$P$` row with a high count
    # character would hang the login thread computing 2^60 MD5s — a denial of service
    # written into a database row.
    forged = "$P$" + "z" + "abcdefgh" + "x" * 22
    assert WordPressPasswordHasher().verify("anything", PREFIX + forged) is False


# ── Django integration ───────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("password,raw", list(_cases()))
def test_django_check_password_and_identify_hasher_agree(settings, password, raw):
    settings.PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "apps.accounts.hashers.WordPressPasswordHasher",
    ]
    encoded = PREFIX + raw
    assert identify_hasher(encoded).algorithm == "wordpress"
    assert check_password(password, encoded)
    assert not check_password("x" + password, encoded)  # prefixed — see above


def test_A_SUCCESSFUL_LOGIN_UPGRADES_THE_HASH_AND_A_FAILED_ONE_DOES_NOT(settings):
    """The upgrade path is the point: this hasher should stop being reachable per-user
    after their first login. If the setter never fired, WordPress MD5 hashes would live in
    the database forever."""
    settings.PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "apps.accounts.hashers.WordPressPasswordHasher",
    ]
    password, wp_modern, *_ = VECTORS[0]
    upgraded = []

    assert check_password(password, PREFIX + wp_modern, setter=upgraded.append)
    assert len(upgraded) == 1 and upgraded[0] == password

    upgraded.clear()
    assert not check_password("wrong", PREFIX + wp_modern, setter=upgraded.append)
    assert upgraded == []


def test_the_hasher_can_never_create_a_hash():
    hasher = WordPressPasswordHasher()
    with pytest.raises(NotImplementedError):
        hasher.encode("password", "salt")
    with pytest.raises(NotImplementedError):
        hasher.salt()


def test_safe_summary_leaks_the_format_and_nothing_else():
    summary = WordPressPasswordHasher().safe_summary(PREFIX + VECTORS[0][2])
    assert summary == {"algorithm": "wordpress", "format": "$P$B"}
    assert VECTORS[0][2][4:] not in str(summary)


# ── wrap_wordpress_hash ──────────────────────────────────────────────────────────────────


@pytest.mark.parametrize("password,raw", list(_cases()))
def test_wrap_preserves_the_wordpress_hash_byte_for_byte(password, raw):
    # The property the cutover relies on: what is stored is exactly what is in
    # wp_users.user_pass, so the import can be verified by comparison.
    wrapped = wrap_wordpress_hash(raw)
    assert wrapped[len(PREFIX):] == raw
    assert is_password_usable(wrapped)


def test_wrap_IS_IDEMPOTENT_so_the_cutover_delta_run_is_safe():
    # Plan-27 re-runs the import against live data. Double-wrapping would produce
    # "wordpress$wordpress$..." — a hash nobody can ever match.
    once = wrap_wordpress_hash(VECTORS[0][1])
    assert wrap_wordpress_hash(once) == once


@pytest.mark.parametrize("junk", ["!locked", "!", "", "   ", None, "not-a-hash"])
def test_wrap_turns_an_unusable_wordpress_row_into_an_unusable_django_password(junk):
    # An account that had no working password in WordPress must land as UNUSABLE, which
    # routes the customer to the reset flow. Storing the literal "!locked" would instead
    # be a password field that silently can never match, with no signal to anyone.
    result = wrap_wordpress_hash(junk)
    assert not is_password_usable(result)


# ── the settings guard ───────────────────────────────────────────────────────────────────


def test_THE_SHIPPED_SETTINGS_PUT_THE_WORDPRESS_HASHER_LAST(settings):
    # Not "somewhere in the list" — LAST. Anything after it would never be reached for a
    # WordPress hash anyway, but position 0 is the one that matters and this asserts the
    # real shipped value rather than a fixture.
    from django.conf import settings as real

    assert real.PASSWORD_HASHERS[-1] == "apps.accounts.hashers.WordPressPasswordHasher"
    assert "WordPress" not in real.PASSWORD_HASHERS[0]


def test_the_check_fires_when_the_wordpress_hasher_is_promoted(settings):
    from apps.accounts.checks import wordpress_hasher_is_not_first

    settings.PASSWORD_HASHERS = [
        "apps.accounts.hashers.WordPressPasswordHasher",
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    ]
    errors = wordpress_hasher_is_not_first(None)
    assert [e.id for e in errors] == ["accounts.E001"]


def test_the_check_is_quiet_for_the_correct_order(settings):
    from apps.accounts.checks import wordpress_hasher_is_not_first

    settings.PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.PBKDF2PasswordHasher",
        "apps.accounts.hashers.WordPressPasswordHasher",
    ]
    assert wordpress_hasher_is_not_first(None) == []


def test_A_PROMOTED_HASHER_REALLY_WOULD_BREAK_SET_PASSWORD(settings):
    """The check's justification, asserted rather than asserted-about.

    If Django ever changed so that a raising `encode()` no longer broke `set_password()`,
    this test would fail and accounts.E001 could be downgraded. Until then it documents
    why the check is an ERROR that aborts `migrate`.
    """
    from django.contrib.auth.hashers import make_password

    settings.PASSWORD_HASHERS = ["apps.accounts.hashers.WordPressPasswordHasher"]
    with pytest.raises(NotImplementedError):
        make_password("any new password")
