"""Verify WordPress password hashes, so 937 migrated customers keep their passwords.

WHY THIS EXISTS. Plan-22 moves ~977 customers off three WooCommerce stores. Their
passwords exist only as hashes — by definition we cannot read them — so the choice is
between this file and mailing every customer a reset link on cutover day. A forced
password reset for the entire customer base, arriving unprompted from a site that just
changed, is indistinguishable from a phishing campaign and would be ignored by most and
distrusted by the rest.

WHAT IT DOES NOT DO. It cannot CREATE a WordPress hash. `encode()` raises. This class is
a one-way door for legacy material: verify on the way in, upgrade to the project default
on the way out, and never write a new one. `must_update()` therefore always returns True,
so the first successful login after migration silently rehashes to PBKDF2 and this code
stops being reachable for that user forever.

── THREE FORMATS, BECAUSE WORDPRESS CHANGED ITS MIND TWICE ──────────────────────────────

  $wp$2y$...   WordPress 6.8+. bcrypt over base64(HMAC-SHA384(password, key="wp-sha384")).
               The pre-hash exists because bcrypt silently truncates at 72 bytes; hashing
               first makes every input exactly 64 base64 chars, so long passwords stop
               being equivalent to their first 72 bytes. NG current is 100% this.
  $P$ / $H$    phpass "portable" — salted MD5 stretched 2^N times. Ancient and weak, but
               84 NG-old plus 2 intl users still have one, and a weak hash we can verify
               is strictly better for them than a reset email they will not trust.
  $2y$/$2a$/$2b$  plain bcrypt, from installs that used PHP's password_hash() directly.

Anything else — `!locked`, an empty string, a truncated row — verifies as False rather
than raising. A malformed hash must fail the login, not 500 the login endpoint.

── STORAGE: `wordpress$` + THE RAW WORDPRESS HASH, BYTE FOR BYTE ────────────────────────

Django resolves a hash to its hasher with `encoded.split("$", 1)[0]` (`identify_hasher`).
Every WordPress hash STARTS with `$`, so storing one verbatim would make that expression
the empty string — and the hasher would claim every `$`-prefixed hash in the database.
A ten-character prefix makes the ownership explicit instead.

The raw hash survives verbatim after the prefix, which is the property that matters at
cutover: `stored[10:]` is exactly what is in `wp_users.user_pass`, so the import can be
proven correct by comparison rather than by re-deriving anything.

── WHY phpass IS VENDORED AND NOT INSTALLED ─────────────────────────────────────────────

The spec reached for `passlib`. It has not shipped since 1.7.4 in 2020, and here it would
serve 86 users. The portable-hash algorithm below is ~25 lines and has not changed since
2006 — it is frozen by the hashes already in the database, which no upstream release can
alter. Vendoring it removes an unmaintained dependency from the security-critical path;
`bcrypt` (pyca, actively maintained) is a real dependency because bcrypt is not 25 lines.
"""

import hashlib
import hmac
from base64 import b64encode

import bcrypt
from django.contrib.auth.hashers import BasePasswordHasher
from django.utils.crypto import constant_time_compare

# ── phpass portable hashes ───────────────────────────────────────────────────────────────

#: phpass's own base64 alphabet. NOT RFC 4648 — the order differs, so the stdlib cannot be
#: substituted here. Frozen by the hashes in the database.
ITOA64 = "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"


def _encode64(data: bytes, count: int) -> str:
    """phpass's `encode64`, ported statement for statement from `class-phpass.php`.

    The awkward shape — the breaks in the middle of the group, the reads one byte ahead —
    is PHP's `$i++` post-increment semantics preserved deliberately. It is not idiomatic
    Python and should not be tidied into something that reads better: the output must
    match byte for byte or every phpass login fails, and the tests pin it against hashes
    generated by the production server's own PHP.
    """
    out: list[str] = []
    i = 0
    while True:
        value = data[i]
        i += 1
        out.append(ITOA64[value & 0x3F])
        if i < count:
            value |= data[i] << 8
        out.append(ITOA64[(value >> 6) & 0x3F])
        if i >= count:
            break
        i += 1
        if i < count:
            value |= data[i] << 16
        out.append(ITOA64[(value >> 12) & 0x3F])
        if i >= count:
            break
        i += 1
        out.append(ITOA64[(value >> 18) & 0x3F])
        if i >= count:
            break
    return "".join(out)


def _phpass_crypt(password: bytes, setting: str) -> str | None:
    """phpass `crypt_private`. Returns the full hash, or None if `setting` is not one.

    MD5 in a loop is indefensible by modern standards, and that is not this file's
    decision to make — it is what 86 existing rows contain. `must_update()` upgrades every
    one of them to PBKDF2 on first login.
    """
    if len(setting) < 12 or setting[:3] not in ("$P$", "$H$"):
        return None
    count_log2 = ITOA64.find(setting[3])
    # phpass's own bounds. Outside them the PHP returns a failure marker rather than
    # looping 2^60 times, and so must this.
    if count_log2 < 7 or count_log2 > 30:
        return None
    salt = setting[4:12].encode("ascii", "ignore")
    if len(salt) != 8:
        return None

    digest = hashlib.md5(salt + password).digest()
    for _ in range(1 << count_log2):
        digest = hashlib.md5(digest + password).digest()
    return setting[:12] + _encode64(digest, 16)


# ── modern WordPress ($wp$) ──────────────────────────────────────────────────────────────

#: WordPress's fixed HMAC key for the bcrypt pre-hash. A domain separator, not a secret —
#: it is a literal in wp-includes/pluggable.php and is identical on every install.
WP_SHA384_KEY = b"wp-sha384"


def _wp_prehash(password: bytes) -> bytes:
    """base64(HMAC-SHA384(password, "wp-sha384")) — WordPress's pre-hash for bcrypt.

    48 raw bytes become 64 base64 characters, comfortably under bcrypt's 72-byte
    truncation point, which is the entire reason the pre-hash exists.
    """
    return b64encode(hmac.new(WP_SHA384_KEY, password, hashlib.sha384).digest())


#: bcrypt's input limit. Everything past this byte has never affected any bcrypt hash.
BCRYPT_MAX_BYTES = 72


def _bcrypt_check(secret: bytes, encoded: str) -> bool:
    """bcrypt verify that returns False instead of raising on a malformed hash.

    THE TRUNCATION IS LOAD-BEARING, NOT DEFENSIVE. pyca/bcrypt 4.0+ RAISES on a secret
    longer than 72 bytes; PHP's `password_verify` silently ignores the excess, which is
    what actually happened when these hashes were written. Passing the full secret through
    would turn "customer has a long password" into an exception caught as a failed login —
    a permanent, unexplainable lockout affecting only customers on the plain `$2y$` rows,
    and only the ones who chose long passwords. The tests pin this against a 108-byte
    password hashed by the production PHP.

    Truncating here is safe for the `$wp$` caller too: its pre-hash is always exactly 64
    base64 characters, so this never fires on that path — which is the whole reason
    WordPress introduced the pre-hash.
    """
    try:
        return bcrypt.checkpw(secret[:BCRYPT_MAX_BYTES], encoded.encode("ascii"))
    except (ValueError, TypeError):
        return False


# ── the Django hasher ────────────────────────────────────────────────────────────────────

#: The prefix that makes `identify_hasher` resolve. `wordpress$` + the raw WP hash.
PREFIX = "wordpress$"


class WordPressPasswordHasher(BasePasswordHasher):
    """Verify-only hasher for hashes imported from WooCommerce. See the module docstring.

    NEVER put this first in `PASSWORD_HASHERS`. `encode()` raises, so a first-position
    entry would break every password set anywhere in the project — including
    `createsuperuser`. `apps.accounts.checks.check_password_hashers_order` fails the
    system check if anyone ever does, because the failure would otherwise surface as an
    unrelated-looking 500 at the first `set_password()`.
    """

    algorithm = "wordpress"

    def salt(self) -> str:
        raise NotImplementedError("WordPress hashes are never created here, only verified")

    def encode(self, password: str, salt: str) -> str:
        raise NotImplementedError(
            "WordPressPasswordHasher is verify-only: it exists to read hashes migrated "
            "from WooCommerce, never to write new ones. If this raised during an ordinary "
            "set_password(), something has put 'wordpress' first in PASSWORD_HASHERS."
        )

    def decode(self, encoded: str) -> dict:
        return {"algorithm": self.algorithm, "hash": encoded[len(PREFIX):]}

    def verify(self, password: str, encoded: str) -> bool:
        if not encoded.startswith(PREFIX):
            return False
        wp_hash = encoded[len(PREFIX):]
        secret = password.encode("utf-8")

        # WordPress 6.8+: "$wp" + a standard bcrypt hash of the HMAC pre-hash.
        if wp_hash.startswith("$wp$"):
            return _bcrypt_check(_wp_prehash(secret), wp_hash[3:])

        # phpass portable.
        if wp_hash[:3] in ("$P$", "$H$"):
            computed = _phpass_crypt(secret, wp_hash)
            return computed is not None and constant_time_compare(computed, wp_hash)

        # Plain bcrypt, straight from PHP's password_hash().
        if wp_hash[:4] in ("$2y$", "$2a$", "$2b$"):
            return _bcrypt_check(secret, wp_hash)

        # "!locked", a truncated row, an empty string: no password can match, and this is
        # a failed login rather than an exception.
        return False

    def must_update(self, encoded: str) -> bool:
        """Always. A WordPress hash is legacy material by definition, so the first
        successful login rehashes to the project default and retires this row."""
        return True

    def safe_summary(self, encoded: str) -> dict:
        wp_hash = encoded[len(PREFIX):] if encoded.startswith(PREFIX) else encoded
        # The FORMAT is safe to surface (it is what tells an admin whether this account is
        # on the ancient MD5 path); the salt and checksum are not, so nothing after the
        # format marker is included.
        return {"algorithm": self.algorithm, "format": wp_hash[:4]}

    def harden_runtime(self, password: str, encoded: str) -> None:
        """No-op, deliberately. The three formats have fixed, unequal costs and there is
        no extra work that would equalise them; pretending otherwise would be theatre."""


def wrap_wordpress_hash(raw: str) -> str:
    """The one place a WordPress hash becomes a Django password field.

    Used by the Plan-22 importer. A hash that is already wrapped is returned unchanged so
    that Plan-27's delta re-runs are idempotent, and anything that is not recognisably a
    WordPress hash — `!locked`, an empty column — becomes an UNUSABLE password rather than
    a stored value that can never match. That distinction is visible to the customer: an
    unusable password sends them down the reset flow, which is correct for an account that
    never had a working password in WordPress either.
    """
    raw = (raw or "").strip()
    if raw.startswith(PREFIX):
        return raw
    if raw.startswith(("$wp$", "$P$", "$H$", "$2y$", "$2a$", "$2b$")):
        return PREFIX + raw
    from django.contrib.auth.hashers import make_password

    return make_password(None)
