# Generated by Django 5.2.16 on 2026-07-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_rating_avg_product_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='legacy_wp_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='testimonials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='usps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
