# Generated by Django 5.2.16 on 2026-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_legacy_wp_id_product_testimonials_and_more'),
        ('core', '0004_country_area_label'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_wp_id__isnull', False)), fields=('legacy_wp_id',), name='uniq_category_legacy_wp_id'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_wp_id__isnull', False)), fields=('legacy_source', 'legacy_wp_id'), name='uniq_product_legacy_ref'),
        ),
    ]
