# Generated by Django 5.2.16 on 2026-08-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productvideo_asset_remove_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
