# Generated by Django 5.2.16 on 2026-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='catalog/thumbs/'),
        ),
    ]
