# Generated by Django 5.2.16 on 2026-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_assignable',
            field=models.BooleanField(default=True),
        ),
    ]
