# Generated by Django 5.2.16 on 2026-07-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_country_area_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('carrier', 'Carrier API')], default='manual', max_length=10)),
                ('carrier_code', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('free_over', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_days', models.PositiveSmallIntegerField()),
                ('max_days', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
                ('countries', models.ManyToManyField(blank=True, related_name='delivery_options', to='core.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('regions', models.ManyToManyField(blank=True, related_name='delivery_options', to='core.region')),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryOptionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight_g', models.IntegerField(default=0)),
                ('max_weight_g', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='delivery.deliveryoption')),
            ],
            options={
                'ordering': ['min_weight_g'],
            },
        ),
    ]
