# Generated by Django 5.2.16 on 2026-07-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_seed_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deliveryoption',
            name='quote_required',
            field=models.BooleanField(default=False),
        ),
    ]
