# Generated by Django 5.2.16 on 2026-08-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_region_centroid'),
        ('delivery', '0004_deliveryoption_disclaimer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigLga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lga_name', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
                ('gig_state_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('home_delivery', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField()),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gig_lgas', to='core.region')),
            ],
            options={
                'verbose_name': 'GIG LGA',
                'unique_together': {('state_name', 'lga_name')},
            },
        ),
    ]
