# Generated by Django 5.2.16 on 2026-08-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_seed_gig_option'),
        ('orders', '0006_order_search_trigram_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('created', 'Waybill created'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('create_unconfirmed', 'Capture unconfirmed — check with GIG'), ('abandoned', 'Abandoned')], default='quoted', max_length=20)),
                ('quote', models.JSONField(default=dict)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waybill', models.CharField(blank=True, max_length=40)),
                ('capture_api_id', models.CharField(blank=True, max_length=64)),
                ('label_url', models.URLField(blank=True)),
                ('last_scan', models.JSONField(default=dict)),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gig_shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'GIG shipment',
            },
        ),
    ]
