# Generated by Django 5.2.16 on 2026-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_gigshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='carrier_service',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
