# Generated by Django 5.2.16 on 2026-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_plan32b_pins_and_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig_centre_id', models.IntegerField(unique=True)),
                ('gig_station_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'GIG centre',
                'ordering': ['name'],
            },
        ),
    ]
