# Generated by Django 5.2.16 on 2026-08-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_seed_intl_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigshipment',
            name='centre',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
