# Generated by Django 5.2.16 on 2026-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_gigshipment_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GIG sender location',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='gigshipment',
            name='origin',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
