# Generated by Django 5.2.16 on 2026-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_seed_ogudu_sender_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderlocation',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='senderlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
