# Generated by Django 5.2.16 on 2026-08-19 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_tax_labels'),
        ('delivery', '0015_senderlocation_lga_senderlocation_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'delivery partner',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lcda_name', models.CharField(max_length=100)),
                ('areas_covered', models.CharField(max_length=300)),
                ('dispatch_zone', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_days', models.PositiveSmallIntegerField(default=1)),
                ('max_days', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('lga_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_zones', to='core.region')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='delivery.deliverypartner')),
            ],
            options={
                'verbose_name': 'partner zone',
                'ordering': ['lga_region__name', 'lcda_name'],
            },
        ),
    ]
