# Generated by Django 5.2.16 on 2026-08-20 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_tax_labels'),
        ('delivery', '0017_seed_brandnpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderlocation',
            name='customer_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='senderlocation',
            name='state_region',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 'state'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_store_locations', to='core.region'),
        ),
    ]
