# Generated by Django 5.2.16 on 2026-08-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_tax_labels'),
        ('delivery', '0018_senderlocation_customer_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeeMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_code', models.CharField(max_length=40, unique=True)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'delivery fee mask',
                'ordering': ['service_code'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_code', models.CharField(max_length=40)),
                ('country_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('area_region', models.ForeignKey(blank=True, limit_choices_to={'level': 'area'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_blocks_as_area', to='core.region')),
                ('state_region', models.ForeignKey(blank=True, limit_choices_to={'level': 'state'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_blocks_as_state', to='core.region')),
            ],
            options={
                'verbose_name': 'delivery block',
                'ordering': ['service_code', 'country_code', 'id'],
            },
        ),
    ]
