# Generated by Django 5.2.16 on 2026-08-21 00:01
"""PartnerShipment + the history backfill.

Orders placed before this migration recorded a partner delivery ONLY as the string
`delivery_option_name = "Door Delivery - {LCDA} ({partner.name})"` (the PartnerZone
docstring's deliberate snapshot-the-name-only ruling). The backfill parses that
string back into a shipment row so the /deliveries table shows every partner
delivery ever, not just post-deploy ones.

`cost` IS taken from the matched zone's current price: partner options first
reached checkout on 2026-08-19 and fee masks only touched partner prices from
2026-08-20, so for this backfill window `charged == raw zone price` by
construction and the current price is the placement price. Where the LCDA matches
no zone, or several zones whose prices disagree, cost stays None — honest unknowns
render as "—", never as a guess.

`delivered_at` is recovered from the order timeline: the `status:delivered`
OrderEvent's timestamp, when one exists — so already-delivered (and
refunded-after-delivery) history answers the "what should the partner invoice us?"
question the same way post-deploy rows will.
"""

import django.db.models.deletion
from django.db import migrations, models


def backfill_partner_shipments(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    OrderEvent = apps.get_model("orders", "OrderEvent")
    DeliveryPartner = apps.get_model("delivery", "DeliveryPartner")
    PartnerZone = apps.get_model("delivery", "PartnerZone")
    PartnerShipment = apps.get_model("delivery", "PartnerShipment")

    created = unmatched = ambiguous = 0
    for partner in DeliveryPartner.objects.all():
        prefix, suffix = "Door Delivery - ", f" ({partner.name})"
        orders = Order.objects.filter(
            delivery_option_name__startswith=prefix,
            delivery_option_name__endswith=suffix,
            partner_shipment__isnull=True,
        )
        for order in orders.iterator():
            lcda = order.delivery_option_name[len(prefix):-len(suffix)]
            zones = list(
                PartnerZone.objects.filter(partner=partner, lcda_name__iexact=lcda)
            )
            if len(zones) == 1:
                z = zones[0]
                zone = {
                    "id": z.pk, "lcda": z.lcda_name, "areas": z.areas_covered,
                    "dispatch_zone": z.dispatch_zone,
                    "min_days": z.min_days, "max_days": z.max_days,
                }
                cost = z.price
            elif zones and len({z.price for z in zones}) == 1:
                # Same LCDA name in several LGAs at ONE price: the money is certain,
                # the exact row is not — snapshot the label only.
                zone, cost = {"lcda": lcda}, zones[0].price
                ambiguous += 1
            else:
                zone, cost = {"lcda": lcda}, None
                if zones:
                    ambiguous += 1
                else:
                    unmatched += 1
            delivered_event = (
                OrderEvent.objects.filter(order=order, type="status:delivered")
                .order_by("created_at")
                .first()
            )
            PartnerShipment.objects.create(
                order=order, partner=partner, zone=zone, cost=cost,
                charged=order.shipping_total,
                delivered_at=delivered_event.created_at if delivered_event else None,
            )
            created += 1
    if created or unmatched or ambiguous:
        print(
            f"\n  partner-shipment backfill: {created} created "
            f"({unmatched} with no matching zone, {ambiguous} ambiguous LCDA matches)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_deliveryfeemask_deliveryblock'),
        ('orders', '0010_order_pickup_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.JSONField(default=dict)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_shipment', to='orders.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='delivery.deliverypartner')),
            ],
            options={
                'verbose_name': 'partner shipment',
            },
        ),
        # Reverse is a no-op on purpose: unapplying this migration drops the whole
        # table anyway, so the backfilled rows go with it.
        migrations.RunPython(backfill_partner_shipments, migrations.RunPython.noop),
    ]
