# Generated by Django 5.2.16 on 2026-08-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0020_partnershipment'),
        ('orders', '0010_order_pickup_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='AajShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('booked', 'Booked — not yet paid'), ('created', 'Shipment created'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('returned', 'Returned to sender'), ('voided', 'Voided'), ('create_unconfirmed', 'Capture unconfirmed — check with AAJ'), ('abandoned', 'Abandoned')], default='quoted', max_length=20)),
                ('quote', models.JSONField(default=dict)),
                ('quote_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_id', models.CharField(blank=True, max_length=40)),
                ('tracking_id', models.CharField(blank=True, max_length=40)),
                ('aaj_shipment_id', models.CharField(blank=True, max_length=40)),
                ('label_url', models.URLField(blank=True)),
                ('last_scan', models.JSONField(default=dict)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_tracked_at', models.DateTimeField(blank=True, null=True)),
                ('origin', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aaj_shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'AAJ shipment',
            },
        ),
    ]
