# Generated by Django 5.2.16 on 2026-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_seed_aaj_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='aajshipment',
            name='carrier_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
