# Generated by Django 5.2.16 on 2026-09-22 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_businessdecisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(default=True, help_text='Uncheck to stop accepting applications. The page stays up.')),
                ('closed_message', models.CharField(blank=True, help_text='What to tell visitors while applications are closed.', max_length=300)),
            ],
            options={
                'verbose_name': 'programme settings',
                'verbose_name_plural': 'programme settings',
            },
        ),
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=160)),
                ('academic_level', models.CharField(max_length=60)),
                ('course_of_study', models.CharField(max_length=120)),
                ('social_handle', models.CharField(blank=True, max_length=120)),
                ('motivation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Not proceeding'), ('withdrawn', 'Withdrew')], default='new', max_length=16)),
                ('staff_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_count', models.PositiveIntegerField(default=1)),
                ('is_resubmission', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_applications', to='core.country')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_program_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'programme application',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='progapp_status_idx'), models.Index(fields=['email'], name='progapp_email_idx'), models.Index(fields=['-created_at'], name='progapp_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'new')), fields=('email',), name='progapp_unique_new_per_email')],
            },
        ),
    ]
