"""Create the StaffInvite table.

THE REVERSE IS PROVABLY NON-DESTRUCTIVE, which is the property `accounts/0003` paid
for the hard way. That migration's reverse deleted four Groups — and because
`get_or_create` on names as generic as `Owner` and `Support` ADOPTS a pre-existing
group, it deleted rows, and memberships, that the forward had never created. A reverse
that destroys data the forward cannot restore is not a reverse.

This one carries no `RunPython` and no `RunSQL` at all: one `CreateModel` and nothing
else. Its inverse drops exactly one table, which nothing else references and which can
only ever contain rows this feature created. There is no pre-existing data for it to
adopt, so there is none for it to destroy.
`test_staff_invites.test_the_invite_migration_cannot_destroy_data_on_the_way_back`
asserts the absence of the data operations rather than trusting this note.

Generated by Django 5.2.16 on 2026-07-29.
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_admin_roles'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_invites', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
