# Generated by Django 5.2.16 on 2026-08-01 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Two columns for three stores becomes a table, before either column holds data.

    THE TWO RemoveFields DROP DATA IRREVERSIBLY — and are safe here for one specific
    reason that was MEASURED rather than assumed: `legacy_wp_id` and `legacy_wp_id_intl`
    are both entirely NULL, on dev and in production, because the only thing that ever
    writes them is the Plan-22 import which has not run yet. Verified immediately before
    this migration was generated (0 non-null of 28 rows locally; the production database
    has never had a migration run against it that populates them).

    If this migration is ever replayed against a database where Plan-22 HAS run, it will
    silently destroy the mapping between customers and their WordPress accounts — which is
    what Plan-23 links order history with. It is safe today and only today; that is the
    whole argument for doing it now rather than adding a third column later.
    """

    dependencies = [
        ('accounts', '0006_user_search_trigram_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legacy_wp_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legacy_wp_id_intl',
        ),
        migrations.AlterField(
            model_name='user',
            name='legacy_source',
            field=models.CharField(blank=True, choices=[('legacy_ng', 'Nigeria — current store'), ('legacy_ng_old', 'Nigeria — old store (dead since Nov 2025)'), ('legacy_intl', 'International (US/UK/CA)')], max_length=20),
        ),
        migrations.CreateModel(
            name='LegacyIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.CharField(choices=[('legacy_ng', 'Nigeria — current store'), ('legacy_ng_old', 'Nigeria — old store (dead since Nov 2025)'), ('legacy_intl', 'International (US/UK/CA)')], max_length=20)),
                ('wp_user_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'legacy identities',
                'constraints': [models.UniqueConstraint(fields=('store', 'wp_user_id'), name='uniq_legacy_identity_store_wp_id')],
            },
        ),
    ]
