# Generated by Django 5.2.16 on 2026-07-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_country_area_label'),
        ('orders', '0005_order_orders_orde_status_adb568_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('awaiting_quote', 'Awaiting quote'), ('quoted', 'Quoted'), ('paid', 'Paid'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='awaiting_quote', max_length=20)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_quote', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='shipping_sh_status_527578_idx')],
            },
        ),
    ]
