# Generated by Django 5.2.16 on 2026-08-06 03:19, then hand-extended with the backfill.
"""Reviews publish immediately (ruling of 2026-08-05); pre-moderation is gone.

The status vocabulary shrinks from pending/approved/rejected to approved/hidden:

* ``pending``  -> ``approved`` — these were reviews awaiting a moderation pass that no
  longer exists. Under the new policy they would have been live from the start.
* ``rejected`` -> ``hidden``   — same operational meaning (kept out of the public list
  and out of the rating), new name.

After the backfill, every product that owned a formerly-pending review gets its
denormalised ``rating_avg``/``rating_count`` recomputed HERE, with the same aggregate
``apps.reviews.services.recompute_product_rating`` uses — newly-live reviews must count
immediately, and no beat task or admin action would otherwise notice these rows.
(``rejected -> hidden`` needs no recompute: neither status ever counted.)

Reverse is ``RunPython.noop``, not ``None`` (a ``None`` reverse makes the whole
migration irreversible): un-publishing cannot be reconstructed — once the statuses are
merged there is no record of which approved rows were once pending — and rolling back
the schema while keeping rows live is the behaviour that loses least.
"""

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models
from django.db.models import Avg, Count


def publish_pending_hide_rejected(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    Product = apps.get_model("catalog", "Product")

    pending_product_ids = list(
        Review.objects.filter(status="pending").values_list("product_id", flat=True)
    )
    Review.objects.filter(status="pending").update(status="approved")
    Review.objects.filter(status="rejected").update(status="hidden")

    for product in Product.objects.filter(id__in=set(pending_product_ids)):
        agg = Review.objects.filter(product=product, status="approved").aggregate(
            avg=Avg("rating"), count=Count("id")
        )
        product.rating_count = agg["count"] or 0
        product.rating_avg = (
            Decimal(str(agg["avg"])).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            if agg["avg"] is not None
            else Decimal("0.00")
        )
        product.save(update_fields=["rating_avg", "rating_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
        # The recompute writes catalog.Product rows; make sure catalog's tables exist
        # in whatever order a fresh database runs these.
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("hidden", "Hidden")],
                default="approved",
                max_length=10,
            ),
        ),
        migrations.RunPython(publish_pending_hide_rejected, migrations.RunPython.noop),
    ]
