# Generated by Django 5.2.16 on 2026-08-29 19:51

import apps.marketing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0011_order_referral_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('meta', 'Meta (Facebook + Instagram)'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('google_ads', 'Google Ads'), ('ga4', 'Google Analytics 4')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('pixel_id', models.CharField(blank=True, max_length=100)),
                ('secondary_id', models.CharField(blank=True, max_length=100)),
                ('browser_enabled', models.BooleanField(default=True)),
                ('server_enabled', models.BooleanField(default=True)),
                ('test_event_code', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MarketingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('purchase_value_basis', models.CharField(choices=[('goods', 'Net goods (after discounts, excl. shipping and tax)'), ('grand_total', 'Grand total (incl. shipping and tax)')], default='goods', max_length=16)),
                ('consent_required_countries', models.JSONField(default=apps.marketing.models._default_consent_countries)),
                ('consent_version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'marketing settings',
            },
        ),
        migrations.CreateModel(
            name='OrderAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_analytics', models.BooleanField(default=False)),
                ('consent_version', models.PositiveIntegerField(default=0)),
                ('click_ids', models.JSONField(blank=True, default=dict)),
                ('pixel_cookies', models.JSONField(blank=True, default=dict)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_user_agent', models.TextField(blank=True)),
                ('event_source_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pii_purged_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_attribution', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('meta', 'Meta (Facebook + Instagram)'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('google_ads', 'Google Ads'), ('ga4', 'Google Analytics 4')], max_length=20)),
                ('event_name', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_events', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='marketing_c_status_72f4eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'event_name', 'event_id'), name='marketing_conversion_event_once')],
            },
        ),
    ]
