# Generated by Django 5.2.16 on 2026-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingchannel',
            name='server_account_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='marketingchannel',
            name='server_destination_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
