# Generated by Django 5.2.16 on 2026-09-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingchannel_server_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderattribution',
            name='consent_status',
            field=models.CharField(blank=True, choices=[('explicit', 'Explicit choice'), ('implied', 'Implied by region')], max_length=16),
        ),
    ]
