# Generated by Django 5.2.16 on 2026-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_country_area_label'),
        ('orders', '0002_order_number_sequence'),
        ('payments', '0002_seed_country_gateways'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_reference', ''), _negated=True), fields=('gateway', 'gateway_reference'), name='uniq_payment_gateway_reference'),
        ),
    ]
