# Generated by Django 5.2.16 on 2026-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refund_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='kind',
            field=models.CharField(default='payment', max_length=10),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
