# Generated by Django 5.2.16 on 2026-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_launch_bank_transfer_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('goods', 'Goods'), ('freight', 'Freight')], default='goods', max_length=10),
        ),
    ]
