# Generated by Django 5.2.16 on 2026-08-22 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_seed_tax_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('store_type', models.CharField(choices=[('toke_store', 'Toke Store'), ('distributor', 'Authorized Distributor')], default='distributor', max_length=32)),
                ('city_text', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('phone_alt', models.CharField(blank=True, max_length=20)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.CharField(blank=True, max_length=160)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name_key', models.CharField(db_index=True, default='', editable=False, max_length=120)),
                ('address_key', models.CharField(db_index=True, default='', editable=False, max_length=300)),
                ('area_region', models.ForeignKey(blank=True, limit_choices_to={'level': 'area'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores_as_area', to='core.region')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_locations', to='core.country')),
                ('state_region', models.ForeignKey(limit_choices_to={'level': 'state'}, on_delete=django.db.models.deletion.PROTECT, related_name='stores_as_state', to='core.region')),
            ],
            options={
                'verbose_name': 'store location',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['area_region', 'is_active'], name='store_area_active_idx'), models.Index(fields=['state_region', 'is_active'], name='store_state_active_idx'), models.Index(fields=['country', 'is_active'], name='store_country_active_idx'), models.Index(fields=['archived_at'], name='store_archived_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('area_region__isnull', False)), fields=('country', 'state_region', 'area_region', 'name_key', 'address_key'), name='store_unique_name_address_in_area'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True), ('area_region__isnull', True)), fields=('country', 'state_region', 'name_key', 'address_key'), name='store_unique_name_address_in_state')],
            },
        ),
    ]
