# Generated by Django 5.2.16 on 2026-07-16 02:04

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_name_trgm'),
        ('core', '0003_seed_countries_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off'), ('free_shipping', 'Free shipping')], max_length=15)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_source', models.CharField(blank=True, max_length=20)),
                ('applies_to_categories', models.ManyToManyField(blank=True, to='catalog.category')),
                ('applies_to_products', models.ManyToManyField(blank=True, to='catalog.product')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='checkout.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='uniq_coupon_code_ci'),
        ),
    ]
